import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os
from datetime import datetime
import streamlit as st

def send_weekly_report(data_dict):
    """
    Sends the weekly SEO & Analytics report via Gmail SMTP.
    data_dict contains the week's metrics.
    """
    try:
        if 'SMTP_SENDER_EMAIL' in st.secrets:
            sender_email = st.secrets['SMTP_SENDER_EMAIL']
            sender_password = st.secrets['SMTP_SENDER_PASSWORD']
            receivers = st.secrets['SMTP_RECEIVERS'].split(',')
        else:
            sender_email = os.environ.get('SMTP_SENDER_EMAIL')
            sender_password = os.environ.get('SMTP_SENDER_PASSWORD')
            receivers = os.environ.get('SMTP_RECEIVERS', '').split(',')
            
        if not sender_email or not sender_password or not receivers:
            print("❌ SMTP Credentials missing. Cannot send email.")
            return False

        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"📈 Inspiria Weekly Growth Report ({datetime.now().strftime('%Y-%m-%d')})"
        msg["From"] = sender_email
        msg["To"] = ", ".join(receivers)

        # Build HTML Email
        html_content = f"""
        <html>
            <body style="font-family: Arial, sans-serif; color: #333;">
                <h2 style="color: #1A73E8;">Inspiria Weekly Growth Report</h2>
                <p>Here is the automated SEO and Analytics breakdown for the past 7 days.</p>
                
                <h3 style="background-color: #f1f3f4; padding: 10px; border-radius: 5px;">📊 Core Analytics (GA4)</h3>
                <ul>
                    <li><b>Organic Sessions:</b> {data_dict.get('organic_sessions', 'N/A')}</li>
                    <li><b>Bounce Rate:</b> {data_dict.get('bounce_rate', 'N/A')}%</li>
                    <li><b>Avg Time on Page:</b> {data_dict.get('avg_time_on_page', 'N/A')}s</li>
                </ul>

                <h3 style="background-color: #f1f3f4; padding: 10px; border-radius: 5px;">🔍 Search Console (GSC)</h3>
                <ul>
                    <li><b>Total Clicks:</b> {data_dict.get('clicks', 'N/A')}</li>
                    <li><b>Total Impressions:</b> {data_dict.get('impressions', 'N/A')}</li>
                    <li><b>Avg CTR:</b> {data_dict.get('avg_ctr', 'N/A')}%</li>
                    <li><b>Avg Keyword Position:</b> {data_dict.get('avg_keyword_position', 'N/A')}</li>
                </ul>

                <h3 style="background-color: #f1f3f4; padding: 10px; border-radius: 5px;">🚀 SEO & Authority (SEMrush)</h3>
                <ul>
                    <li><b>Domain Authority (DR):</b> {data_dict.get('avg_dr', 'N/A')}</li>
                    <li><b>Total Backlinks:</b> {data_dict.get('total_backlinks', 'N/A')}</li>
                    <li><b>Keywords in Top 10:</b> {data_dict.get('keywords_top_10', 'N/A')}</li>
                </ul>
                
                <hr>
                <p style="font-size: 12px; color: #777;">This email was automatically generated by the Inspiria AI Growth Agent via GitHub Actions.</p>
            </body>
        </html>
        """
        
        msg.attach(MIMEText(html_content, "html"))

        print("Connecting to Gmail SMTP...")
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            # We remove spaces from the app password if the user copied them
            server.login(sender_email, sender_password.replace(' ', ''))
            server.sendmail(sender_email, receivers, msg.as_string())
            
        print(f"✅ Weekly report emailed successfully to {len(receivers)} recipients!")
        return True
        
    except Exception as e:
        print(f"❌ Failed to send email: {e}")
        return False
